edition: 1.0.0
name: container-demo
access: {{ access }}
vars:
  region: cn-shenzhen
services:
  customContainer-demo:
    component: devsapp/fc
    props:
      region: ${vars.region}
      service:
        name: container-demo
        internetAccess: true
      function:
        name: cpp-event-function
        description: cpp event function demo
        caPort: 9000
        memorySize: 256
        handler: not-used
        timeout: 60
        initializationTimeout: 30
        initializer: not-used
        runtime: custom-container
        customContainerConfig:
          image: registry-vpc.cn-shenzhen.aliyuncs.com/fc-demo/fc-cpp-event:v0.1
        codeUri: ./code
# https://github.com/devsapp/fc
