edition: 1.0.0
name: container-demo
access: {{ access }}
vars:
  region: cn-shenzhen
services:
  customContainer-demo:
    component: devsapp/fc
    props:
      region: ${vars.region}
      service:
        name: container-demo
        role:
          name: container-demo-DefaultRole
          policies:
            - AliyunContainerRegistryReadOnlyAccess
        internetAccess: true
      function:
        name: aspdotnetcore-http-function
        description: asp .netcore http function demo
        caPort: 80
        memorySize: 512
        handler: not-used
        timeout: 60
        runtime: custom-container
        customContainerConfig:
          image: registry-vpc.cn-shenzhen.aliyuncs.com/fc-demo/fc-asp-http:v0.1
        codeUri: ./code

      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST

      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              serviceName: container-demo
              functionName: aspdotnetcore-http-function
              methods:
                - GET
                - POST
# 函数计算FC组件文档参考地址：https://github.com/devsapp/fc
